spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/metro
    username: postgres
    password: postgres

message:
  token: ${TOKEN_MESSAGE:"token"}