name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://projeto-esteira-suporte.onrender.com/actuator/health)
          echo "API status: $STATUS"

      - name: Ping Frontend
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://metro-front-tuna.onrender.com)
          echo "Frontend status: $STATUS"
